export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const FETCH_ACTIVE_MEETINGS = "FETCH_ACTIVE_MEETINGS";
export const FETCH_INACTIVE_MEETINGS = "FETCH_INACTIVE_MEETINGS";
export const CREATE_MEETING = "CREATE_MEETING";
export const FETCH_MEETING_BY_ID = "FETCH_MEETING_BY_ID";
